forge "http://forge.puppetlabs.com"

mod "camptocamp/augeas", "0.0.1"
mod "example42/apache", "2.1.2"
mod "example42/mysql", "2.1.0"
mod "example42/php", "2.0.13"
mod "example42/puppi", "2.1.1"

mod "puppetlabs/apt", "1.3.0"
mod "puppetlabs/stdlib", "4.1.0"
mod "puppetlabs/nodejs", "0.4.0"

mod 'symfony2', :path => '/vagrant/support/puppet/modules/symfony2'